export const skillsData = [
  "C",
  "C++",
  "JavaScript",
  "TypeScript",
  "Python",
  "React.js",
  "Node.js",
  "Express.js",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "MUI",
  "Flask",
  "RESTful APIs",
  "AWS Certified Solutions Architect – Associate",
  "Oracle SQL",
  "PostgreSQL",
  "MongoDB",
  "Git & GitHub",
  "Docker",
  "Jira",
  "Jest",
];
